# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1 # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
        name: PyDocStyle
        files: ^(src/|scripts/)
        args:
          - --select=D101,D102,D103
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Black
        types: [python]
        files: ^(src/|scripts/)
        args:
          - -S
  - repo: local
    hooks:
      - id: site_generator
        name: Site Generator
        entry: python scripts/site_generator.py
        language: python
        types: [python]
