name: Benchmark PR

on:
  push:
    branches:
      - "benchmark-*.*.*"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create PR
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          pr_label: automerge
          destination_branch: "main"
          pr_body: "This is an automated PR."
          github_token: ${{ secrets.JINA_DEV_BOT }}

      - name: merge PR
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
         merge-method: merge
         token: ${{ secrets.JINA_DEV_BOT }}
         pull-request-number: ${{steps.open-pr.outputs.pr_number}}
