name: Github Page

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: "Why?"
        required: true
        default: "Just casually!"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.82.0"
          extended: true

      - name: Build
        run: |
          cd docs
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.JINA_DEV_BOT }}
          publish_branch: gh-pages
          publish_dir: ./docs/public
