name: Github Page

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: "Why?"
        required: true
        default: "Just casually!"

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Generate site
        run: python scripts/site_generator.py

      - name: Commit files
        run: |
          git config user.name "Jina Dev Bot"
          git config user.email bot@jina.ai
          git add -A
          git commit -m "chore: generated site contents" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JINA_DEV_BOT }}
          branch: ${{ github.ref }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.82.0"
          extended: true

      - name: Build
        run: |
          cd docs
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.JINA_DEV_BOT }}
          publish_branch: gh-pages
          publish_dir: ./docs/public
