name: PR Tests

on: pull_request

jobs:
  check-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: check black
        run: |
          pip install black==20.8b1
          black -S --check src/
          black -S --check scripts/

  check-site-generation:
    runs-on: ubuntu-latest
    needs: check-black
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: check site generation
        run: |
          pip install requests==2.26.0 packaging==21.0
          python scripts/site_generator.py
          git status
          git diff-index --quiet HEAD -- || exit 1

      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        if: ${{ github.actor == 'jina-bot' }}
        env:
          GITHUB_TOKEN: "${{ secrets.JINA_DEV_BOT }}"
          MERGE_LABELS: automerge
          MERGE_METHOD: merge
          MERGE_COMMIT_MESSAGE: automatic
          MERGE_FILTER_AUTHOR: jina-bot
          MERGE_FORKS: false
          MERGE_DELETE_BRANCH: true
